INSERT INTO TypeTrx(CodTypTrx,DescTrx,Nature) VALUES
('01','PRIX DE LA CHAMBRE','DB'),
('02','LIT ADDITIONNEL','DB'),
('03','TÉLÉPHONE INTERRUBAIN','DB'),
('04','PHOTOCOPIE','DB'),
('05','INTERNET','DB'),
('06','RESTAURANT','DB'),
('07','BAR TERRASSE','DB'),
('08','DÉPOT ARGENT','CR'),
('09','PAIEMENT','CR')
